package repoquality

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCheckCoverageEnforcesThresholds(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/lab\n\ngo 1.26\n")
	writeFile(t, filepath.Join(root, "alpha", "alpha.go"), "package alpha\n")
	writeFile(t, filepath.Join(root, "beta", "beta.go"), "package beta\n")
	writeFile(t, filepath.Join(root, "generated", "generated.go"), "// Code generated by tool. DO NOT EDIT.\npackage generated\n")
	writeFile(t, filepath.Join(root, "coverage.out"), strings.Join([]string{
		"mode: set",
		"example.com/lab/alpha/alpha.go:1.1,2.2 8 1",
		"example.com/lab/beta/beta.go:1.1,2.2 2 0",
		"example.com/lab/generated/generated.go:1.1,2.2 50 0",
	}, "\n")+"\n")

	result, err := CheckCoverage(root, coverageOptions{profile: "coverage.out", aggregate: 90, pkg: 80})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Failures) != 2 || !strings.Contains(result.Report, "example.com/lab/alpha 100.0%") ||
		!strings.Contains(result.Report, "example.com/lab/beta 0.0%") {
		t.Fatalf("result = %#v", result)
	}
	if strings.Contains(result.Report, "example.com/lab/generated") {
		t.Fatal("generated file was counted")
	}

	passing, err := CheckCoverage(root, coverageOptions{profile: "coverage.out", aggregate: 50, pkg: 0})
	if err != nil || len(passing.Failures) != 0 {
		t.Fatalf("passing = (%#v, %v)", passing, err)
	}
}

func TestCheckCoverageRejectsMalformedProfiles(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/lab\n")
	writeFile(t, filepath.Join(root, "alpha.go"), "package alpha\n")
	if _, err := CheckCoverage(root, coverageOptions{profile: "missing.out"}); err == nil {
		t.Fatal("missing profile was accepted")
	}
	writeFile(t, filepath.Join(root, "empty.out"), "")
	if _, err := CheckCoverage(root, coverageOptions{profile: "empty.out"}); err == nil {
		t.Fatal("empty profile was accepted")
	}
	writeFile(t, filepath.Join(root, "badmode.out"), "not-a-mode\n")
	if _, err := CheckCoverage(root, coverageOptions{profile: "badmode.out"}); err == nil {
		t.Fatal("bad mode was accepted")
	}
	writeFile(t, filepath.Join(root, "badrecord.out"), "mode: set\nnot-a-record\n")
	if _, err := CheckCoverage(root, coverageOptions{profile: "badrecord.out"}); err == nil {
		t.Fatal("bad record was accepted")
	}
	writeFile(t, filepath.Join(root, "outside.out"), "mode: set\nother.com/alpha.go:1.1,2.2 1 1\n")
	if _, err := CheckCoverage(root, coverageOptions{profile: "outside.out"}); err == nil {
		t.Fatal("outside module record was accepted")
	}
	writeFile(t, filepath.Join(root, "missingfile.out"), "mode: set\nexample.com/lab/nope.go:1.1,2.2 1 1\n")
	if _, err := CheckCoverage(root, coverageOptions{profile: "missingfile.out"}); err == nil {
		t.Fatal("missing source was accepted")
	}
	writeFile(t, filepath.Join(root, "generated-only.out"), "mode: set\nexample.com/lab/generated/generated.go:1.1,2.2 1 1\n")
	writeFile(t, filepath.Join(root, "generated", "generated.go"), "// Code generated by tool. DO NOT EDIT.\npackage generated\n")
	if _, err := CheckCoverage(root, coverageOptions{profile: "generated-only.out"}); err == nil {
		t.Fatal("generated-only profile was accepted")
	}
	writeFile(t, filepath.Join(root, "go.mod"), "go 1.26\n")
	if _, err := CheckCoverage(root, coverageOptions{profile: "coverage.out"}); err == nil {
		t.Fatal("module-less go.mod was accepted")
	}
}

func writeFile(t *testing.T, path, contents string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
}
