package repoquality

import (
	"bytes"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"errors"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCoverageRejectsNonfiniteAndOutOfRangeMinima(t *testing.T) {
	for _, value := range []float64{math.NaN(), math.Inf(1), math.Inf(-1), -1, 100.1} {
		for _, options := range []coverageOptions{{aggregate: value}, {pkg: value}} {
			if _, err := CheckCoverage(t.TempDir(), options); err == nil || !strings.Contains(err.Error(), "finite numbers between 0 and 100") {
				t.Fatalf("minima %#v: %v", options, err)
			}
		}
	}
}

func TestCoverageRejectsAmbiguousOverflowingAndEmptyAccounting(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/lab\n")
	writeFile(t, filepath.Join(root, "alpha.go"), "package alpha\n")
	for name, profile := range map[string]string{
		"unknown mode":     "mode: surprise\nexample.com/lab/alpha.go:1.1,2.2 1 1\n",
		"mode only":        "mode: count\n",
		"zero statements":  "mode: set\nexample.com/lab/alpha.go:1.1,2.2 0 1\n",
		"count overflow":   "mode: count\nexample.com/lab/alpha.go:1.1,2.2 1 9223372036854775808\n",
		"block overflow":   "mode: count\nexample.com/lab/alpha.go:1.1,2.2 9223372036854775808 1\n",
		"total overflow":   "mode: count\nexample.com/lab/alpha.go:1.1,2.2 9223372036854775807 1\nexample.com/lab/alpha.go:3.1,4.2 1 1\n",
		"set count":        "mode: set\nexample.com/lab/alpha.go:1.1,2.2 1 2\n",
		"zero coordinate":  "mode: set\nexample.com/lab/alpha.go:0.1,2.2 1 1\n",
		"reversed lines":   "mode: set\nexample.com/lab/alpha.go:2.1,1.2 1 1\n",
		"reversed columns": "mode: set\nexample.com/lab/alpha.go:1.2,1.1 1 1\n",
		"duplicate block":  "mode: set\nexample.com/lab/alpha.go:1.1,2.2 1 1\nexample.com/lab/alpha.go:1.1,2.2 1 1\n",
		"source traversal": "mode: set\nexample.com/lab/../outside.go:1.1,2.2 1 1\n",
		"source alias":     "mode: set\nexample.com/lab/./alpha.go:1.1,2.2 1 1\n",
		"source backslash": "mode: set\nexample.com/lab/sub\\alpha.go:1.1,2.2 1 1\n",
	} {
		t.Run(name, func(t *testing.T) {
			writeFile(t, filepath.Join(root, "coverage.out"), profile)
			if _, err := CheckCoverage(root, coverageOptions{profile: "coverage.out"}); err == nil {
				t.Fatal("invalid profile accepted")
			}
		})
	}
}

func TestCoverageGeneratedMarkerFollowsGoSemantics(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module\t\"example.com/lab\" // module identity\n")
	writeFile(t, filepath.Join(root, "normal.go"), "package normal\n// Code generated by a test tool. DO NOT EDIT.\n")
	writeFile(t, filepath.Join(root, "generated.go"), "// License header\n\n\n\n\n\n// Code generated by a test tool. DO NOT EDIT.\npackage normal\n")
	writeFile(t, filepath.Join(root, "coverage.out"), "mode: atomic\nexample.com/lab/normal.go:1.1,2.2 2 3\nexample.com/lab/generated.go:1.1,2.2 100 0\n")
	result, err := CheckCoverage(root, coverageOptions{profile: "coverage.out", aggregate: 100, pkg: 100})
	if err != nil || len(result.Failures) != 0 || !strings.Contains(result.Report, "100.0% (2/2)") {
		t.Fatalf("generated marker accounting = %#v, %v", result, err)
	}
}

func TestContainedPathResolvesMissingLeavesAndRejectsSymlinkEscapes(t *testing.T) {
	root := t.TempDir()
	outside := t.TempDir()
	if relative, err := containedPath(root, filepath.Join(root, "absent", "nested", "file.md")); err != nil || relative != "absent/nested/file.md" {
		t.Fatalf("missing contained leaf = %q, %v", relative, err)
	}
	link := filepath.Join(root, "linked")
	if err := os.Symlink(outside, link); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	if _, err := containedPath(root, filepath.Join(link, "missing.md")); !errors.Is(err, ErrPathEscape) {
		t.Fatalf("missing leaf below escaping symlink = %v", err)
	}
	dangling := filepath.Join(root, "dangling")
	if err := os.Symlink(filepath.Join(outside, "absent"), dangling); err != nil {
		t.Fatal(err)
	}
	if _, err := containedPath(root, dangling); err == nil {
		t.Fatal("dangling symlink accepted")
	}
}

func TestCoverageRejectsSourceSymlinkOutsideModule(t *testing.T) {
	root, outside := t.TempDir(), t.TempDir()
	writeFile(t, filepath.Join(root, "go.mod"), "module example.com/lab\n")
	writeFile(t, filepath.Join(outside, "alpha.go"), "package alpha\n")
	if err := os.Symlink(filepath.Join(outside, "alpha.go"), filepath.Join(root, "alpha.go")); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	writeFile(t, filepath.Join(root, "coverage.out"), "mode: set\nexample.com/lab/alpha.go:1.1,2.2 1 1\n")
	if _, err := CheckCoverage(root, coverageOptions{profile: "coverage.out"}); err == nil || !strings.Contains(err.Error(), "escapes the module") {
		t.Fatalf("external source accepted: %v", err)
	}
}

func TestRepositoryPathsHaveOnePortableIdentity(t *testing.T) {
	root := t.TempDir()
	for _, relative := range []string{"", ".", "../a", "docs/../a", "docs//a", "/a", `docs\a`, "C:/a", "a\x00b"} {
		if _, err := repositoryPath(root, relative); err == nil {
			t.Errorf("ambiguous path %q accepted", relative)
		}
	}
	if got, err := repositoryPath(root, "docs/a b.md"); err != nil || got != filepath.Join(root, "docs", "a b.md") {
		t.Fatalf("portable relative path = %q, %v", got, err)
	}
}

func TestLinksSupportURLQueriesAndRejectPlatformSpecificPaths(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "docs", "a b.md"), "existing\n")
	writeFile(t, filepath.Join(root, "README.md"), "[query](docs/a%20b.md?raw=1#heading) [remote](HTTPS://example.com) [mail](MAILTO:a@example.com) [query-only](?raw=1)\n")
	result, err := CheckLinks(root)
	if err != nil || len(result.Failures) != 0 || !strings.Contains(result.Report, "1 links") {
		t.Fatalf("valid URL paths = %#v, %v", result, err)
	}
	for _, target := range []string{"/docs/a.md", "C%3A/a.md", `docs\a.md`, "docs/a%00.md", "docs/%xx.md"} {
		writeFile(t, filepath.Join(root, "README.md"), "[invalid]("+target+")\n")
		result, err := CheckLinks(root)
		if err != nil || len(result.Failures) != 1 || !strings.Contains(result.Failures[0], "invalid local link") {
			t.Errorf("invalid URL path %q = %#v, %v", target, result, err)
		}
	}
}

func TestPolicyJSONRejectsDuplicateMembersAndMalformedUnicode(t *testing.T) {
	root := t.TempDir()
	for _, content := range []string{
		`{"lockfileVersion":3,"lockfileVersion":3,"packages":{"":{}}}`,
		`{"lockfileVersion":3,"packages":{"":{"license":"\ud800"}}}`,
		`{"lockfileVersion":3,"packages":{"":{"dev":false,"dev":true}}}`,
	} {
		writeFile(t, filepath.Join(root, "package-lock.json"), content)
		if _, err := CheckDependencies(root); err == nil || !strings.Contains(err.Error(), "invalid policy JSON") {
			t.Fatalf("ambiguous dependency policy accepted: %v", err)
		}
	}
}

func TestNPMIntegrityIsCanonicalFullSHA512(t *testing.T) {
	valid := "sha512-" + base64.StdEncoding.EncodeToString(bytes.Repeat([]byte{42}, 64))
	if !validNPMIntegrity(valid) {
		t.Fatal("valid SHA-512 integrity rejected")
	}
	for _, invalid := range []string{"sha512-A", "sha512-AAAA", "sha512-" + strings.Repeat("=", 88), valid + "\n", strings.Replace(valid, "sha512", "sha256", 1)} {
		if validNPMIntegrity(invalid) {
			t.Errorf("invalid integrity %q accepted", invalid)
		}
	}
}

func TestPolicyFileReadsAreBoundedAndRegular(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "policy.json")
	writeFile(t, path, "123456789")
	if _, err := readFileLimited(path, 8); err == nil {
		t.Fatal("oversized policy file accepted")
	}
	if _, err := readFileLimited(root, 8); err == nil {
		t.Fatal("directory accepted as a policy file")
	}
	data, err := readFileLimited(path, 9)
	if err != nil || string(data) != "123456789" {
		t.Fatalf("exact byte limit = %q, %v", data, err)
	}
}

func TestMediaReferencesAndAssetPathsStayWithinRepository(t *testing.T) {
	root, asset := mediaFixture(t)
	for _, reference := range []string{"../outside.md", "/outside.md", `C:\outside.md`, "docs/../README.md"} {
		asset.ReferencedBy = []string{reference}
		writeMediaManifest(t, root, asset)
		result, err := CheckMedia(root)
		if err != nil || !strings.Contains(joinFailures(result.Failures), "invalid reference path") {
			t.Errorf("reference %q = %#v, %v", reference, result, err)
		}
	}
	asset.ReferencedBy = []string{"README.md"}
	asset.Path = "docs/media/../media/ok.png"
	writeMediaManifest(t, root, asset)
	result, err := CheckMedia(root)
	if err != nil || !strings.Contains(joinFailures(result.Failures), "invalid asset path") {
		t.Fatalf("aliased asset path = %#v, %v", result, err)
	}
}

func TestMediaRejectsExternalReferenceSymlinkAndNullHistory(t *testing.T) {
	root, asset := mediaFixture(t)
	asset.ReplacementHistory = json.RawMessage("null")
	writeMediaManifest(t, root, asset)
	result, err := CheckMedia(root)
	if err != nil || !strings.Contains(joinFailures(result.Failures), "missing replacementHistory") {
		t.Fatalf("null history = %#v, %v", result, err)
	}
	asset.ReplacementHistory = json.RawMessage("[]")
	outside := filepath.Join(t.TempDir(), "outside.md")
	writeFile(t, outside, asset.Path)
	if err := os.Symlink(outside, filepath.Join(root, "external.md")); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	asset.ReferencedBy = []string{"external.md"}
	writeMediaManifest(t, root, asset)
	result, err = CheckMedia(root)
	if err != nil || !strings.Contains(joinFailures(result.Failures), "reference escapes repository") {
		t.Fatalf("external reference = %#v, %v", result, err)
	}
}

func TestImageDimensionsRejectSpoofsAndOverflow(t *testing.T) {
	root := t.TempDir()
	pngHeader := make([]byte, 24)
	copy(pngHeader[1:4], "PNG")
	binary.BigEndian.PutUint32(pngHeader[16:20], 10)
	binary.BigEndian.PutUint32(pngHeader[20:24], 20)
	path := filepath.Join(root, "spoof.png")
	if err := os.WriteFile(path, pngHeader, 0o644); err != nil {
		t.Fatal(err)
	}
	if _, _, err := assetDimensions(path); err == nil {
		t.Fatal("PNG substring spoof accepted")
	}
	path = filepath.Join(root, "image.svg")
	for _, content := range []string{
		`<svg width="18446744073709551617" height="1"/>`,
		`<svg width="0" height="1"/>`,
		`<!-- <svg width="10" height="20"/> --><svg/>`,
		`<wrapper><svg width="10" height="20"/></wrapper>`,
	} {
		writeFile(t, path, content)
		if _, _, err := assetDimensions(path); err == nil {
			t.Fatalf("invalid SVG dimensions accepted: %s", content)
		}
	}
	writeFile(t, path, `<svg width='10' height='20'/>`)
	if width, height, err := assetDimensions(path); err != nil || width != 10 || height != 20 {
		t.Fatalf("single-quoted SVG dimensions = %d, %d, %v", width, height, err)
	}
}

func TestWebPDimensionHeadersValidateContainerBounds(t *testing.T) {
	path := filepath.Join(t.TempDir(), "image.webp")
	data := make([]byte, 26)
	copy(data[:4], "RIFF")
	binary.LittleEndian.PutUint32(data[4:8], 18)
	copy(data[8:16], "WEBPVP8L")
	binary.LittleEndian.PutUint32(data[16:20], 5)
	data[20], data[21], data[22], data[23], data[24] = 0x2f, 3, 0x81, 2, 1
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatal(err)
	}
	if width, height, err := assetDimensions(path); err != nil || width != 260 || height != 1035 {
		t.Fatalf("lossless bit fields = %d, %d, %v", width, height, err)
	}
	for _, offset := range []int{4, 16, 24} {
		invalid := bytes.Clone(data)
		invalid[offset] = 0xff
		if err := os.WriteFile(path, invalid, 0o644); err != nil {
			t.Fatal(err)
		}
		if _, _, err := assetDimensions(path); err == nil {
			t.Errorf("invalid WebP field at %d accepted", offset)
		}
	}
}

func mediaFixture(t *testing.T) (string, mediaAsset) {
	t.Helper()
	root := t.TempDir()
	path := filepath.Join(root, "docs", "media", "ok.png")
	writePNG(t, path, 2, 3)
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	digest, err := fileSHA256(path)
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(root, "README.md"), "docs/media/ok.png\n")
	asset := mediaAsset{
		Path: "docs/media/ok.png", Status: "current", Width: 2, Height: 3,
		Bytes: info.Size(), MaxBytes: 10000, SHA256: digest,
		Origin: "project-authored-vector", Alt: "Test image", License: "Apache-2.0",
		RightsStatus: "approved-for-public-repository", RightsBasis: "Test fixture",
		RightsReviewedAt: "2026-09-04", ReviewerRole: "maintainer", SourceRevision: "test-fixture",
		ReplacementHistory: json.RawMessage("[]"), ReferencedBy: []string{"README.md"},
	}
	writeMediaManifest(t, root, asset)
	return root, asset
}

func writeMediaManifest(t *testing.T, root string, asset mediaAsset) {
	t.Helper()
	data, err := json.Marshal(mediaManifest{SchemaVersion: 2, Assets: []mediaAsset{asset}})
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(root, "docs", "media", "manifest.json"), string(data))
}
