package assurance

import (
	"encoding/json"
	"fmt"
	"strings"
)

type listReport struct {
	Schema              string      `json:"schema"`
	RegistrySchema      string      `json:"registry_schema"`
	EvidenceStatus      string      `json:"evidence_status"`
	ApplicabilityStatus string      `json:"applicability_status"`
	Invariants          []Invariant `json:"invariants"`
}

type inspectionReport struct {
	Schema              string    `json:"schema"`
	RegistrySchema      string    `json:"registry_schema"`
	EvidenceStatus      string    `json:"evidence_status"`
	ApplicabilityStatus string    `json:"applicability_status"`
	Invariant           Invariant `json:"invariant"`
}

func (registry Registry) ListJSON() ([]byte, error) {
	if len(registry.invariants) == 0 {
		return nil, ErrInvalidRegistry
	}
	data, err := json.Marshal(listReport{ListSchema, Schema, "not-executed", "not-evaluated", registry.List()})
	return data, err
}

func (registry Registry) InspectJSON(id string) ([]byte, error) {
	invariant, err := registry.Inspect(id)
	if err != nil {
		return nil, err
	}
	data, err := json.Marshal(inspectionReport{InspectionSchema, Schema, "not-executed", "not-evaluated", invariant})
	return data, err
}

const metadataNotice = "Declared metadata. Checks not run; case applicability not evaluated.\n"

func (registry Registry) ListText() string {
	var output strings.Builder
	output.WriteString("ASSURANCE REGISTRY\n")
	output.WriteString(metadataNotice)
	output.WriteByte('\n')
	for _, invariant := range registry.invariants {
		fmt.Fprintf(&output, "%s  [%s]\n  %s\n", invariant.ID, strings.ReplaceAll(invariant.Lifecycle, "-", " "), invariant.Statement)
	}
	output.WriteString("\nInspect: fartapp assurance inspect <ID>\n")
	return output.String()
}

func (registry Registry) InspectText(id string) (string, error) {
	invariant, err := registry.Inspect(id)
	if err != nil {
		return "", err
	}
	var output strings.Builder
	fmt.Fprintf(&output, "ASSURANCE %s\n", invariant.ID)
	output.WriteString(metadataNotice)
	fmt.Fprintf(&output, "\n%s\n\nLifecycle: %s\nOwner responsibility: %s\nApplicability: %s\nTolerance: %s: %s\nMilestone: %s\n",
		invariant.Statement, strings.ReplaceAll(invariant.Lifecycle, "-", " "), invariant.Owner, invariant.Applicability,
		invariant.Tolerance.ID, invariant.Tolerance.Description, invariant.Milestone)
	output.WriteString("\nDeclared Go checks:\n")
	if len(invariant.Checks) == 0 {
		output.WriteString("  None; implementation remains planned.\n")
	}
	for _, check := range invariant.Checks {
		fmt.Fprintf(&output, "  %s: %s %s (%s)\n", check.ID, check.Package, check.Name, check.File)
	}
	for _, group := range []struct {
		name   string
		values []EvidenceReference
	}{{"Evidence references", invariant.Evidence}, {"Counterexample references", invariant.Counterexamples}} {
		fmt.Fprintf(&output, "\n%s:\n", group.name)
		if len(group.values) == 0 {
			output.WriteString("  None declared.\n")
		}
		for _, reference := range group.values {
			fmt.Fprintf(&output, "  %s: %s\n", reference.Path, reference.Description)
		}
	}
	output.WriteString("\nSeparate verification benchmarks:\n")
	if len(invariant.RelatedBenchmarks) == 0 {
		output.WriteString("  None declared.\n")
	}
	for _, reference := range invariant.RelatedBenchmarks {
		fmt.Fprintf(&output, "  %s:%s [%s]: %s\n", reference.Namespace, reference.ID, reference.Relationship, reference.Scope)
	}
	fmt.Fprintf(&output, "\nOpen direction: %s\n", invariant.Direction)
	return output.String(), nil
}

// Markdown renders the complete registry, including its open work. It contains
// no timestamps or execution conclusions, and is checked for source drift.
func (registry Registry) Markdown() string {
	var output strings.Builder
	output.WriteString("# Invariant reference\n\nGenerated from [the canonical registry](../internal/assurance/registry.json).\nDo not edit this file directly. See [assurance semantics and maintenance](ASSURANCE.md).\n\n")
	output.WriteString("These are declared metadata and evidence references. Checks have not been executed\nby this rendering, and applicability to a case has not been evaluated. Lifecycle\nis an internal candidate status, not a passing result or a ratification decision.\nOwners name repository responsibilities, not approving people. Verification\nbenchmarks occupy a separate namespace; shared IDs do not establish equivalence.\n\n")
	output.WriteString("| ID | Lifecycle | Owner responsibility | Milestone | Invariant |\n| --- | --- | --- | --- | --- |\n")
	for _, value := range registry.invariants {
		fmt.Fprintf(&output, "| [%s](#%s) | %s | %s | %s | %s |\n", value.ID, strings.ToLower(value.ID), value.Lifecycle, value.Owner, value.Milestone, markdownText(value.Statement))
	}
	for _, value := range registry.invariants {
		fmt.Fprintf(&output, "\n## %s\n\n%s\n\n", value.ID, markdownText(value.Statement))
		fmt.Fprintf(&output, "Lifecycle: `%s`. Owner responsibility: `%s`. Milestone: `%s`.\n\nApplicability: %s\n\nTolerance profile `%s`: %s\n\nOpen direction: %s\n\n",
			value.Lifecycle, value.Owner, value.Milestone, markdownText(value.Applicability), value.Tolerance.ID, markdownText(value.Tolerance.Description), markdownText(value.Direction))
		output.WriteString("Declared Go checks:\n\n")
		if len(value.Checks) == 0 {
			output.WriteString("No executable check declared; implementation remains planned.\n")
		}
		for _, check := range value.Checks {
			fmt.Fprintf(&output, "- `%s`: `%s` in [%s](../%s), package `%s`.\n", check.ID, check.Name, check.File, check.File, check.Package)
		}
		for _, group := range []struct {
			name   string
			values []EvidenceReference
		}{{"Evidence references", value.Evidence}, {"Counterexample references", value.Counterexamples}} {
			fmt.Fprintf(&output, "\n%s:\n\n", group.name)
			if len(group.values) == 0 {
				output.WriteString("None declared; this evidence remains open.\n")
			}
			for _, reference := range group.values {
				fmt.Fprintf(&output, "- [%s](../%s): %s\n", reference.Path, reference.Path, markdownText(reference.Description))
			}
		}
		output.WriteString("\nSeparate verification benchmarks:\n\n")
		if len(value.RelatedBenchmarks) == 0 {
			output.WriteString("No relationship declared.\n")
		}
		for _, reference := range value.RelatedBenchmarks {
			fmt.Fprintf(&output, "- `%s:%s`, `%s`: %s\n", reference.Namespace, reference.ID, reference.Relationship, markdownText(reference.Scope))
		}
	}
	return output.String()
}

func markdownText(value string) string {
	return strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", "\\", "\\\\", "`", "\\`", "*", "\\*", "_", "\\_", "[", "\\[", "]", "\\]", "|", "\\|").Replace(value)
}
